workflows:
  ios-development:
    name: iOS Development Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: MyCoachFinder
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_IDENTIFIER: "MyCoachFinder"
      node: 20.19.5
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      
      - name: Sync Capacitor assets to iOS
        script: |
          npx cap sync ios
      
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
      
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - info@boothtml.com
        notify:
          success: true
          failure: true

  ios-production:
    name: iOS App Store Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - ios_signing
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_IDENTIFIER: "MyCoachFinder"
        APP_STORE_ID: "6503015097"
      node: 20.19.5
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install

      - name: Sync Capacitor assets to iOS
        script: |
          npx cap sync ios

      - name: Set up code signing
        script: |
          set -e
          set -x

          # Initialize keychain
          keychain initialize

          # Decode and save certificate
          echo "$CM_CERTIFICATE" | base64 --decode > /tmp/certificate.p12

          # Decode and save provisioning profile
          echo "$CM_PROVISIONING_PROFILE" | base64 --decode > /tmp/profile.mobileprovision

          # Import certificate to keychain
          security import /tmp/certificate.p12 -k ~/Library/Keychains/codemagic.keychain-db -P "$CM_CERTIFICATE_PASSWORD" -T /usr/bin/codesign

          # Install provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_UUID=$(security cms -D -i /tmp/profile.mobileprovision | grep -a UUID | grep -o "[-A-Z0-9]\{36\}")
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.mobileprovision

          # Set provisioning profile in Xcode project
          cd ios/App
          /usr/libexec/PlistBuddy -c "Set :buildSettings:PROVISIONING_PROFILE_SPECIFIER $PROFILE_UUID" App.xcodeproj/project.pbxproj || true
          /usr/libexec/PlistBuddy -c "Set :buildSettings:DEVELOPMENT_TEAM 374793446M" App.xcodeproj/project.pbxproj || true

      - name: Increment build number
        script: |
          cd ios/App
          agvtool new-version -all $(($BUILD_NUMBER + 1))

      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false

      email:
        recipients:
          - info@boothtml.com
        notify:
          success: true
          failure: true
