integrations:
  app_store_connect: codemagic_api_key

workflows:
  ios-development:
    name: iOS Development Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
      ios_signing:
        distribution_type: development
        bundle_identifier: MyCoachFinder
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_IDENTIFIER: "MyCoachFinder"
      node: 20.19.5
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      
      - name: Sync Capacitor assets to iOS
        script: |
          npx cap sync ios
      
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Set up code signing
        script: |
          # Decode and save certificate
          echo "$CM_CERTIFICATE" | base64 --decode > /tmp/certificate.p12
          
          # Decode and save provisioning profile
          PROFILE_PATH="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILE_PATH"
          echo "$CM_PROVISIONING_PROFILE" | base64 --decode > "$PROFILE_PATH/profile.mobileprovision"
          
          # Verify files
          ls -lh /tmp/certificate.p12
          ls -lh "$PROFILE_PATH/profile.mobileprovision"
          
          # Import certificate to keychain
          security import /tmp/certificate.p12 \
            -k ~/Library/Keychains/codemagic.keychain-db \
            -P "$CM_CERTIFICATE_PASSWORD" \
            -T /usr/bin/codesign
          
          # Set partition list
          security set-key-partition-list \
            -S apple-tool:,apple:,codesign: \
            -s -k "" ~/Library/Keychains/codemagic.keychain-db
          
          # Apply code signing settings
          xcode-project use-profiles
      
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - hannes@example.com
        notify:
          success: true
          failure: true
