workflows:
  ios-development:
    name: iOS Development Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: MyCoachFinder
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_IDENTIFIER: "MyCoachFinder"
      node: 20.19.5
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      
      - name: Sync Capacitor assets to iOS
        script: |
          npx cap sync ios
      
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
      
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - info@boothtml.com
        notify:
          success: true
          failure: true

  ios-production:
    name: iOS App Store Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - ios_signing
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_IDENTIFIER: "MyCoachFinder"
        APP_STORE_ID: "6503015097"
      node: 20.19.5
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install

      - name: Sync Capacitor assets to iOS
        script: |
          npx cap sync ios

      - name: Set up keychain
        script: |
          keychain initialize

      - name: Set up code signing
        script: |
          set -e
          set -x

          # Debug password (remove after fixing)
          echo "Password length: ${#CM_CERTIFICATE_PASSWORD}"
          echo "First 3 chars: ${CM_CERTIFICATE_PASSWORD:0:3}***"

          # Get the default keychain path and trim whitespace
          KEYCHAIN_PATH=$(security default-keychain -d user | tr -d '"' | xargs)
          echo "Keychain path: $KEYCHAIN_PATH"

          # Decode and save certificate
          echo "$CM_CERTIFICATE" | base64 --decode > /tmp/distribution.p12

          # Verify certificate file was created
          ls -la /tmp/distribution.p12

          # Try to verify the certificate with password first
          echo "Testing certificate password..."
          openssl pkcs12 -info -in /tmp/distribution.p12 -passin pass:"$CM_CERTIFICATE_PASSWORD" -noout || true

          # Import certificate to keychain using security command directly
          # Use quotes around password to handle special characters
          security import /tmp/distribution.p12 -k "$KEYCHAIN_PATH" -P "${CM_CERTIFICATE_PASSWORD}" -T /usr/bin/codesign -T /usr/bin/security

          # Set key partition list (required for codesigning)
          security set-key-partition-list -S apple-tool:,apple: -s -k "" "$KEYCHAIN_PATH"

          # Decode and install provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$CM_PROVISIONING_PROFILE" | base64 --decode > /tmp/profile.mobileprovision

          PROFILE_UUID=$(security cms -D -i /tmp/profile.mobileprovision | grep -a UUID | grep -o "[-A-Z0-9]\{36\}")
          echo "Provisioning Profile UUID: $PROFILE_UUID"
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.mobileprovision

          # List installed profiles
          echo "Installed provisioning profiles:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/

          # Verify certificate is in keychain
          echo "Certificates in keychain:"
          security find-identity -v -p codesigning "$KEYCHAIN_PATH"

      - name: Set up Xcode project signing
        script: |
          cd ios/App
          xcode-project use-profiles

      - name: Increment build number
        script: |
          cd ios/App
          agvtool new-version -all $(($BUILD_NUMBER + 1))

      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false

      email:
        recipients:
          - info@boothtml.com
        notify:
          success: true
          failure: true
