#!/bin/bash

echo "======================================"
echo "Codemagic Credentials Verification"
echo "======================================"
echo ""

echo "1. CM_CERTIFICATE_APPSTORE"
echo "   Characters: $(wc -c < ios_distribution_p12_base64.txt)"
echo "   Expected: 4272"
echo ""
echo "   To copy to clipboard (if xclip installed):"
echo "   cat ios_distribution_p12_base64.txt | xclip -selection clipboard"
echo ""
echo "   To view:"
echo "   cat ios_distribution_p12_base64.txt"
echo ""
echo "---"
echo ""

echo "2. CM_CERTIFICATE_PASSWORD_APPSTORE"
echo "   Value: MyCoachFinder2024!"
echo ""
echo "---"
echo ""

echo "3. CM_PROVISIONING_PROFILE_APPSTORE"
echo "   Characters: $(wc -c < appstore_profile_base64.txt)"
echo "   Expected: 16288"
echo ""
echo "   To copy to clipboard (if xclip installed):"
echo "   cat appstore_profile_base64.txt | xclip -selection clipboard"
echo ""
echo "   To view:"
echo "   cat appstore_profile_base64.txt"
echo ""
echo "======================================"
echo ""
echo "Files location:"
pwd
echo ""
echo "Next: Add these 3 variables to Codemagic"
echo "Go to: https://codemagic.io/apps"
echo "======================================"
